import { FC, ReactNode } from "react";
import Head from "next/head";
import { Header } from "src/components/organisms/Header";
import { Footer } from "src/components/organisms/Footer";
import { Content } from "src/components/organisms/Content";

type Props = {
  title: string;
  h1text: string;
  children: ReactNode;
};

export const Template: FC<Props> = ({ title, h1text, children }) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Content h1text={h1text} />
      <Footer />
    </div>
  );
};
